# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
    ]
